### ISSUE TITLE
Module 'SDL' could not be found

### ISSUE THREAD

**Issue by jasonvfx** [Looking-Glass/UnrealPlugin_Issues#5]
I am trying to load the plugin to review something and I am getting this error after I drop the three plugins from the SDK into the folder 
"Plugin 'SDL' failed to load because module 'SDL' could not be found. Please ensure the plugin is properly in stalled, otherwise consider disabling the plugin for this project"
I am using Unreal Engine 4.22.3 ( you guys specify 4.21 and 4.22 work with the plugins) and SDK 1.2.1
Otherwise everything is a fresh install. 
Please let me know how to proceed

**Comment by alxdncn** [comment]
Hi @jasonvfx, apologies on the long delay getting back to you. It seems like you didn't transfer over the "SDL" folder which should have come with the plugin.

We just released a new version of the plugin, I would try updating to that and trying again! You can get it here: https://lookingglassfactory.com/devtools/holoplay-plugin-for-unreal-engine
